export interface PoolPerson {
  name: string;
  winner: "TCU" | "Georgia" | "Neither";
  score: number;
  points: number;
  gamesCorrect: number;
}

export const PoolPeople: Array<PoolPerson> = [
  {
    name: "Declan",
    winner: "Neither",
    score: 75,
    points: 20,
    gamesCorrect: 20,
  },
  {
    name: "Mark K",
    winner: "Georgia",
    score: 52,
    points: 19,
    gamesCorrect: 19,
  },
  {
    name: "Mark S",
    winner: "Georgia",
    score: 44,
    points: 18,
    gamesCorrect: 18,
  },
  {
    name: "Paul",
    winner: "Georgia",
    score: 54,
    points: 18,
    gamesCorrect: 18,
  },
  {
    name: "Kelly",
    winner: "Georgia",
    score: 60,
    points: 18,
    gamesCorrect: 18,
  },
  {
    name: "Stephanie",
    winner: "Neither",
    score: 63,
    points: 18,
    gamesCorrect: 18,
  },
  {
    name: "Maddie",
    winner: "Neither",
    score: 68,
    points: 18,
    gamesCorrect: 18,
  },
  {
    name: "Anthony",
    winner: "Georgia",
    score: 65,
    points: 17,
    gamesCorrect: 17,
  },
  {
    name: "Ron",
    winner: "Georgia",
    score: 52,
    points: 17,
    gamesCorrect: 17,
  },
  {
    name: "Eddie",
    winner: "TCU",
    score: 68,
    points: 16,
    gamesCorrect: 16,
  },
  {
    name: "Austin",
    winner: "TCU",
    score: 57,
    points: 16,
    gamesCorrect: 16,
  },
  {
    name: "Leslie",
    winner: "Neither",
    score: 68,
    points: 16,
    gamesCorrect: 16,
  },
  {
    name: "Diane",
    winner: "Neither",
    score: 60,
    points: 15,
    gamesCorrect: 15,
  },
  {
    name: "April",
    winner: "Neither",
    score: 63,
    points: 15,
    gamesCorrect: 15,
  },
  {
    name: "Adam",
    winner: "Georgia",
    score: 52,
    points: 15,
    gamesCorrect: 15,
  },
  {
    name: "Quinn",
    winner: "Georgia",
    score: 45,
    points: 15,
    gamesCorrect: 15,
  },
  {
    name: "David",
    winner: "Georgia",
    score: 50,
    points: 15,
    gamesCorrect: 15,
  },
  {
    name: "Drugan",
    winner: "Neither",
    score: 61,
    points: 15,
    gamesCorrect: 15,
  },
  {
    name: "Mark L",
    winner: "Neither",
    score: 37,
    points: 14,
    gamesCorrect: 14,
  },
  {
    name: "Henry",
    winner: "TCU",
    score: 60,
    points: 14,
    gamesCorrect: 14,
  },
  {
    name: "Curtis",
    winner: "TCU",
    score: 42,
    points: 14,
    gamesCorrect: 14,
  },
  {
    name: "Hannah",
    winner: "Neither",
    score: 44,
    points: 13,
    gamesCorrect: 13,
  },
  {
    name: "Lauren",
    winner: "Neither",
    score: 37,
    points: 13,
    gamesCorrect: 13,
  },
  {
    name: "Joan",
    winner: "Neither",
    score: 27,
    points: 13,
    gamesCorrect: 13,
  },
  {
    name: "Brian",
    winner: "Georgia",
    score: 56,
    points: 13,
    gamesCorrect: 13,
  },
  {
    name: "Leah",
    winner: "Georgia",
    score: 35,
    points: 13,
    gamesCorrect: 13,
  },
  {
    name: "Mackenzie",
    winner: "Georgia",
    score: 53,
    points: 13,
    gamesCorrect: 13,
  },
  {
    name: "Rita",
    winner: "Neither",
    score: 42,
    points: 14,
    gamesCorrect: 12,
  },
  {
    name: "Owen",
    winner: "Georgia",
    score: 65,
    points: 12,
    gamesCorrect: 12,
  },
  {
    name: "George",
    winner: "Georgia",
    score: 65,
    points: 11,
    gamesCorrect: 11,
  },
  {
    name: "Bob",
    winner: "Georgia",
    score: 56,
    points: 11,
    gamesCorrect: 11,
  },
  {
    name: "Kieran",
    winner: "Georgia",
    score: 62,
    points: 11,
    gamesCorrect: 11,
  },
];